# Generated by Django 4.1.5 on 2023-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_genre_movie_género_alter_genero_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.CharField(choices=[('A', 'Excelente'), ('B', 'Buena'), ('C', 'Regular'), ('D', 'Mala'), ('E', 'Muy mala')], default='C', max_length=4, verbose_name='Valoración'),
        ),
    ]
