# Generated by Django 4.1.5 on 2023-02-08 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
